name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - 'main'
  pull_request:

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache yarn cache
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: yarn-cache-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: yarn install --immutable --non-interactive

      - name: ESLint
        run: yarn eslint .

      - name: Prettier
        run: yarn prettier --check .
